# Generated by Django 4.1.7 on 2023-04-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_caterories_listing_comment_bid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing_Caterories',
            new_name='Listing_Categories',
        ),
    ]
