# Generated by Django 4.1.7 on 2023-04-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_listing_caterories_listing_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing_Categories',
            new_name='Listing_Category',
        ),
    ]
